interledgerjs/five-bells-shared

- errors/already-exists-error.js
- errors/invalid-modification-error.js
- errors/invalid-uri-parameter-error.js
- errors/not-found-error.js
- errors/unauthorized-error.js
- errors/unmet-condition-error.js
- errors/unprocessable-entity-error.js
- index.js
Update all error classes to ES6 class format and expose them on the module's public interface.
> Expose error classes

- lib/persistent-model-mixin.js
Also, don't call `fromDatabaseModel` on `upsert` since `upsert` doesn't return anything useful for sqlite.
> [FEATURE] Add findOrCreate

- schemas/ConditionFulfillment.json
> [FEATURE] BooleanAndFulfillment

- schemas/Account.json
Needs to be merged in conjunction with https://github.com/interledger/five-bells-ledger/pull/90.
> Add ability to disable accounts

- schemas/Account.json
For https://github.com/interledger/five-bells-connector/issues/51 and https://github.com/interledger/five-bells-connector/issues/50 and https://github.com/interledger/five-bells-ledger/issues/105
> [FEATURE] Add "ledger" field to Account

- lib/db.js
Fixes https://github.com/interledger/five-bells-ledger/issues/93
> [TASK] db.init()

- schemas/Subscription.json
> Enforce URI for subject and target

- package.json
- utils/hashPassword.js
- utils/makeCaseAttestation.js
This function is part of the sender refactor.
> [FEATURE] makeCaseAttestation, hashPassword

- lib/config.js
https://facebook.github.io/immutable-js/docs/#/Map/mergeDeep
> FIX: Recursively merge common config and local config

- index.js
- lib/notificationScheduler.js
- lib/persistent-knex-model-mixin.js
- package.json
Also makes breaking (fixing?) changes to the knex model's `save` and `destroy` methods.
> [FEATURE] NotificationScheduler

- schemas/Notification.json
See https://github.com/interledger/five-bells-ledger/pull/146\#issuecomment-184915123
> Include condition fulfillment in Notification

- package.json
Includes a change in SSL/TLS certificate configuration that is not backwards
compatible, but is not currently being used in any components.
> Update package version to 9.2.1

- lib/config.js
Unit tests cover this function
> Small refactor of validateEnvConfig

- bin/bump.sh
- package.json
Moves https://github.com/interledger/five-bells-connector/pull/99 to here
and installs a command, `version-bump` that can be used in packages that depend
on five-bells-shared
> Moves version bumping script from connector to here

- schemas/Account.json
- test/data/account.json
- test/data/index.js
- test/validatorSpec.js
> FIX: Account schema fingerprint

- lib/config.js
- test/configSpec.js
I got LGTM for this code on PR 105. 
PR 105, however, pointed to a wrong merge target. 
Therefore I am merging this PR instead.  This is the same code with PR105.
> Add database configuration variables.

- bin/bump.sh
> chore: Remove debug output from bump.sh and fix

- .eslintignore
- jsdoc.json
- lib/config.js
- lib/notificationScheduler.js
- package.json
- utils/jsonSigning.js
This is for the new Interledger.org website, we need to customize the JSDoc template.
> Switch to custom JSDoc template

- .gitignore
- jsdoc.json
- package.json
- scripts/publish_web.js
Generate documentation for interledger.org
> Automatically generate JS docs

- lib/notificationScheduler.js
This is for https://github.com/interledger/five-bells-ledger/pull/263
> Refactor NotificationScheduler

- schemas/IlpHeader.json
as per IL-RFC-3 after https://github.com/interledger/rfcs/pull/44
> feat: add expiresAt and executionCondition to IlpHeader schema

- errors/already-rolled-back-error.js
- errors/transfer-not-conditional-error.js
- utils/jsonSigning.js
These errors will be used by five-bells-ledger.
> feat: {AlreadyRolledBack,TransferNotConditional}Error

- schemas/Message.json
Related to https://github.com/interledgerjs/five-bells-ledger/issues/346
> feat: Add Message.from/Message.to

- schemas/Routes.json
Related to https://github.com/interledgerjs/ilp-connector/issues/270
> feat: Route.destination_{precision,scale}

- circle.yml
- schemas/Condition.json
- schemas/ConditionFulfillment.json
BREAKING CHANGE: Change format for crypto-conditions to draft-02.
> feat: update to new crypto-condition format

- package.json
> fix: fixes #184

- schemas/FundsTemplate.json
- schemas/IlpHeader.json
- schemas/IlpPayment.json
- schemas/RejectionMessage.json
- schemas/Routes.json
- schemas/index.js
> BREAKING RejectionMessage, new ilp-packet format

- circle.yml
- package.json
- schemas/LiquidityCurve.json
- schemas/Routes.json
Companion to https://github.com/interledgerjs/ilp-routing/pull/40
> feat: define optional paths field in route broadcast schema

- schemas/Routes.json
Companion to https://github.com/interledgerjs/ilp-connector/pull/350
> feat: configure curve broadcasts

- schemas/Message.json
See https://github.com/interledgerjs/ilp-plugin-bells/pull/142
> fix: allow message.data as fallback

- schemas/Fulfillment.json
- schemas/index.js
Needed for interledgerjs/five-bells-ledger#436
> feat(schemas): add fulfillment-with-data schema
