interledgerjs/five-bells-shared

lib/db.js

I'm working on the notary, which uses dependency injection to cleanly separate between classes and instantiated objects.
The shared Database class currently depends on a logger instance just to be defined, which is bad. Instead the logger should be passed in via the constructor. Fortunately, a facility for that already exists.

Allow shared DB class to be defined without logger

---

lib/config.js

Currently, this is [implemented in -ledger](https://github.com/interledger/five-bells-ledger/blob/master/src/services/config.js#L20-L42). But since many Five Bells components will hold keys, it makes sense to move the key config management to -shared.

Manage key config

---

lib/db.js

See https://github.com/sequelize/sequelize/commit/43e0e194a18b2b6be9a1f3ad3f08e9e234320c99
Also, `options` is sometimes undefined now.

[FEATURE] Savepoint hack update: sequelize ≥3.14.2

---

index.js
lib/persistent-knex-model-mixin.js

1. There is  an ongoing discussion about if we should replace persistent-knex-model-mixin with a similar module that does not use a class.  We can discuss this further, but in the meantime, I propose to merge the current implementation to get Oracle integration and testing going.  
2. @gip has kindly agreed to review this.

Use Knex instead of Sequelize to support Oracle

---

lib/db.js

If you're passing in a database URI it's useful to check to ensure it is using the correct one
We might also want to create an option to completely disable the use of sqlite so that it is not use accidentally in production

Log db uri

---

middlewares/error-handler.js

Previously the status and body were being set manually. However, this left the Content-Type unchanged. When the error was just a string this would cause parsing errors on the client side because the Content-Type was still set to application/json

Use Koa ctx.throw for handling errors

---

lib/config.js
package.json
test/configSpec.js

config = require('lib/config').loadConfig('prefix') // prefix is the env var
prefix
config.getIn(['db', 'uri']) // returns config value at a given path
config.toJS() //returns the object representation of the config

BREAKING: Config#loadConfig returns Immutable.Map config object

---

lib/db.js
package.json

Since we're dealing with financial applications, we should be using the most conservative [transaction isolation level](https://en.wikipedia.org/wiki/Isolation_(database_systems)#Isolation_levels): `SERIALIZABLE`.
Also, the ledger was running into concurrent update issues when processing multiple transfers simultaneously (see https://github.com/interledger/five-bells-ledger/issues/135 and https://github.com/interledger/five-bells-shared/issues/64). The database was failing -- as it should -- when multiple transactions were attempted concurrently. However, the ledger was responding to the client with `HTTP 500` errors instead of simply retrying the failed database transactions. This adds retry logic for the errors `'could not serialize access due to concurrent update'` and `'could not …

Default to SERIALIZABLE isolation level and retry failed db transactions

---

lib/config.js
test/configSpec.js

Configuration for enabling client certificate authentication:
Example,
```
LEDGER_AUTH_CLIENT_CERT_ENABLED (default: false, requires PUBLIC_HTTPS=true)
CONNECTOR_SSL_KEY (Server wide private key. Requires CERTIFICATE and PUBLIC_HTTPS=true)
CONNECTOR_SSL_CERTIFICATE (Server wide certificate Requires KEY. Requires PUBLIC_HTTPS=true)
CONNECTOR_SSL_CRL (Optional. Certificate Revokation List requires PUBLIC_HTTPS=true and SSL_{KEY|CERTIFICATE})
CONNECTOR_SSL_CA (Optional. Required if Certificate Authority of clients is not part of system CAs. Requires PUBLIC_HTTPS=true and SSL_{KEY|CERTIFICATE})
```
Additional tests
TODO:
Validation for all environment configuration variables

Add authentication configuration

---

lib/config.js
lib/notificationScheduler.js
package.json
test/configSpec.js

The configuration already allows the server to operate behind an HTTP reverse proxy, however, it does not allow the proxy to use a path prefix. With this patch the server can operate at a sub-path behind a proxy.
For example, you may be running a ledger in AWS at `http://10.0.0.1:3000`, but it actually exposed via a front proxy at `https://example.com/ledger`. With this patch you can accomplish this by passing `LEDGER_PUBLIC_PATH=/ledger`.
This PR also fixes some very minor issues:
* Crash while generating error message that a server was run in production without a secret key
* JSDoc was broken and CI wasn't set up correct to detect that

Allow public path prefix

---

lib/config.js
test/configSpec.js

Instead of storing a string path to files, store the contents of the TLS files
as buffers in memory

BREAKING: Read TLS crt, crl, key, and ca into memory

---

package.json

Includes:
799621d Fix crash when no secret key is provided in prod.
9082d39 Allow configuration of a public path prefix.
69a0609 Fix: Fail CI when JSDoc fails
6d27922 Fix failing JSDoc generation
dc4675e Turn ensureLeadingSlash into a function
0fcb989 BREAKING: Read TLS crt, crl, key, and ca into memory

Update to 10.0.0

---

lib/config.js
test/configSpec.js

The `PUBLIC_*` options are intended to configure the public-facing URL of the server. They should not affect anything else. Their purpose is to allow the user to configure the ledger's public URI if it is located behind a reverse proxy or load balancer.
This splits `PUBLIC_HTTPS` into two options `USE_HTTPS` and `PUBLIC_HTTPS`:
* `USE_HTTPS` - Enable HTTPS server (defaults to `false`)
* `PUBLIC_HTTPS` - Whether public URLs are HTTPS URLs (defaults to value of `USE_HTTPS`)
This PR is technically a breaking change because it changes the behavior of a config option. However I'm not aware of anyone using HTTPS yet, so nobody should be affected. The upgrade procedure is to change your config from `XXX_PUBLIC_HTTPS=true` to `XXX_USE_HTTPS=true` if you want the server to listen with TLS enabled. …

Fix: PUBLIC_HTTPS option should not affect server

---

lib/config.js
package.json
test/configSpec.js

- Use Object.freeze to seal config object
- Maintains get() and getIn() config property accessors
`get()` now supports property path syntax as specified by lodash.get
https://lodash.com/docs#get
Breaking change:
Nested config objects are now regular JS objects. toJ() no longer
required.
Example:
Old: `config.get('db').JS()`  (requires toJS() because it return an Immutable.Map)
New: `config.get('db')` (now returns regular object)

BREAKING: Remove Immutable.js dependency

---

bin/bump.sh

Example error message that was previously not shown
npm ERR! extraneous: deep-freeze-node@1.1.2
/Users/alan/Projects/five-bells-shared/node_modules/deep-freeze-node

Fix: Log errors during version bump script

---

lib/config.js
lib/model-mixin.js
lib/model.js
lib/uri-manager.js
package.json

Breaking changes:
https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings
There was a bug in lodash@3 when merging objects with Buffer properties
Fixed in v4:
https://github.com/lodash/lodash/commit/4a4e54479a6eecd916a0e39d400c54bcbba51c31

FIX: Update to lodash@4

---

package.json
schemas/PublicKeyRSA.json
test/data/signData.json
test/jsonSigningSpec.js
utils/jsonSigning.js

@naoitoi please review when you have a minute.
I noticed in some cases the public keys for JCS were failing JSON validation because they were not in Base64URL format. I changed `jsonSigning.js` to return public keys as Base64URL-encoded strings, and also added schema validation for the signature. This required changing `signData.json`, so the format matches the schema. Finally, I removed the `Base64.json` format as a possible RSA exponent (since it should now be `Base64URL.json`

Comply with JCS by Base64URL-encoding keys

---

lib/config.js
test/configSpec.js

When NODE_ENV=production, loadConfig will try to parse ed25519 keys for
the Connector, which does not require this keypair
The change here is backwards compatible.

Fix: Optionally parse ed25519

---

bin/bump.sh
bin/ci-publish.sh
package.json

Prevents npm publish errors (only publish on bump commits)
TODO
- Update five-bells-ledger, five-bells-notary, and five-bells-connector

Create ci-publish npm task

---

bin/ci-publish.sh

Set bash options. Turn off debug output (otherwise leaks env variables)

ci: fix ci-publish

---

lib/config.js

Example of error:
```
LEDGER_DB_URI=sqlite:// LEDGER_USE_HTTPS=false LEDGER_AUTH_CLIENT_CERT_ENABLED=false npm start
> five-bells-ledger@11.0.0 start /Users/alan/Projects/five-bells-ledger
> node src/app.js
/Users/alan/Projects/five-bells-ledger/node_modules/five-bells-shared/lib/config.js:225
throw new ServerError(
^
ServerError: Missing ledger_TLS_KEY or ledger_TLS_CERTIFICATE
at validateEnvConfig (/Users/alan/Projects/five-bells-ledger/node_modules/five-bells-shared/lib/config.js:225:11)
```

fix: correctly parse auth config

---

errors/invalid-body-error.js

Previously the debug output told you which `additionalProperties` clause was being violated, but not the name of the offending property. That information is contained in `dataPath`. So by printing `dataPath` in the case of an `additionalProperties` error, we get a bit better information about what's wrong.

Better debug out for additionalProperties errors

---

README.md

Explain best practices for our logger `mag`.
We are currently making life difficult for ourselves, we could use the mag module instead of passing around logger instances.

Better info about mag

---

schemas/Base64.json
schemas/FundsTemplate.json

Also fixes the `Base64` schema.
```
> (new RegExp("^(?:[A-Za-z0-9+\/]{4}\\n?)*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)$")).test( Buffer.from('abc').toString('base64') )
false
```

feat: add credit.{rejected,rejection_message}

---

lib/config.js
test/configSpec.js

Trailing slashes can mess up the base_uri, so it's best to just always remove them.

feat: remove trailing slashes from base_uri

---

schemas/Message.json

For https://github.com/interledgerjs/five-bells-ledger/issues/349

fix: allow "account" in both Message schemas

---

schemas/RpcRequest.json
schemas/RpcResponse.json

* Allow `RpcRequest.params` to be an array (used by `broadcast_routes`)
* Don't allow `RpcResponse.id` to be `null`.

fix: update RpcReq/Res types

---

schemas/Account.json
schemas/Identifier.json

This regex is used by five-bells-ledger and ilp-kit to verify usernames, so it shouldn't allow weird email address looking things.
Also changed it so it doesn't allow multiple consecutive dashes in usernames.

fix: switch to a sensible Identifier schema

---

circle.yml
lib/validator.js

- Adds additional exception details if schema cannot be loaded
- Changes CI configuration so that `nvm` is not installed again (the build container has it already installed)

Adds additional exception details if schema cannot be loaded

---

errors/already-exists-error.js
errors/already-rolled-back-error.js
errors/database-error.js
errors/invalid-body-error.js
errors/invalid-modification-error.js
errors/invalid-uri-error.js
errors/invalid-uri-parameter-error.js
errors/not-found-error.js
errors/server-error.js
errors/transfer-not-conditional-error.js
errors/unauthorized-error.js
errors/unmet-condition-error.js
errors/unprocessable-entity-error.js
middlewares/error-handler.js

By adding a status property we can get rid of most of the custom errors handlers.
This PR is a stepping stone in a long-standing quest to get rid of five-bells-shared in favor of more widely used modules created by the Node community.

feat: make errors more declarative

---

schemas/FundsTemplate.json

Ledgers should not try to validate ILP-layer data.
Five Bells Ledger, for example, allows arbitrary memos to be placed on funds (`memo`) and transfers (`additional_info`). The one exception is the `rejection_message` which the ledger attempts to validate according to some schema. It shouldn't.

feat: allow any rejection message
